export const names = [
    "Aaden",
    "Aaliyah",
    "Aarav",
    "Aaron",
    "Ab",
    "Abagail",
    "Abb",
    "Abbey",
    "Abbie",
    "Abbigail",
    "Abbott",
    "Abby",
    "Abdiel",
    "Abdul",
    "Abdullah",
    "Abe",
    "Abel",
    "Abelardo",
    "Abie",
    "Abigail",
    "Babe",
    "Babette",
    "Baby",
    "Babymale",
    "Bailee",
    "Bailey",
    "Baker",
    "Baldwin",
    "Ballard",
    "Bama",
    "Bambi",
    "Banks",
    "Barb",
    "Barbara",
    "Barbie",
    "Barbra",
    "Barnard",
    "Barnett",
    "Barney",
    "Barnie",
    "Caddie",
    "Cade",
    "Caden",
    "Cadence",
    "Cael",
    "Caesar",
    "Caiden",
    "Cailyn",
    "Cain",
    "Caitlin",
    "Caitlyn",
    "Caitlynn",
    "Cal",
    "Caldonia",
    "Cale",
    "Caleb",
    "Caleigh",
    "Calhoun",
    "Cali",
    "Calista",
    "Dabney",
    "Dafne",
    "Dagmar",
    "Dagny",
    "Dahlia",
    "Daija",
    "Daijah",
    "Daisey",
    "Daisha",
    "Daisie",
    "Daisy",
    "Daisye",
    "Daja",
    "Dakoda",
    "Dakota",
    "Dakotah",
    "Dale",
    "Dalia",
    "Dallas",
    "Dallin",
    "Ean",
    "Earl",
    "Earle",
    "Earlean",
    "Earlene",
    "Earley",
    "Earlie",
    "Earline",
    "Early",
    "Earnest",
    "Earnestine",
    "Eartha",
    "Easter",
    "Easton",
    "Eathel",
    "Ebb",
    "Ebba",
    "Ebbie",
    "Eben",
    "Ebenezer",
    "Fabian",
    "Fabiola",
    "Fae",
    "Fairy",
    "Faith",
    "Fallon",
    "Falon",
    "Fannie",
    "Fanny",
    "Fannye",
    "Farah",
    "Faron",
    "Farrah",
    "Farrell",
    "Farris",
    "Fate",
    "Fatima",
    "Faustino",
    "Fawn",
    "Fay",
    "Gabe",
    "Gabriel",
    "Gabriela",
    "Gabriella",
    "Gabrielle",
    "Gael",
    "Gaetano",
    "Gage",
    "Gaige",
    "Gail",
    "Gaines",
    "Gaither",
    "Gale",
    "Galen",
    "Galilea",
    "Gannon",
    "Gardner",
    "Garett",
    "Garey",
    "Garfield",
    "Hadassah",
    "Haden",
    "Hadley",
    "Haiden",
    "Hailee",
    "Hailey",
    "Hailie",
    "Hakeem",
    "Hakim",
    "Hal",
    "Halbert",
    "Hale",
    "Haleigh",
    "Haley",
    "Hali",
    "Halie",
    "Hall",
    "Halle",
    "Halley",
    "Hallie",
    "Ian",
    "Ibrahim",
    "Ica",
    "Icey",
    "Icie",
    "Icy",
    "Ida",
    "Idabelle",
    "Idamae",
    "Idell",
    "Idella",
    "Iesha",
    "Ieshia",
    "Ignacio",
    "Ignatius",
    "Ignatz",
    "Ike",
    "Ila",
    "Ilah",
    "Ilda",
    "Jabari",
    "Jabbar",
    "Jabez",
    "Jacalyn",
    "Jace",
    "Jacey",
    "Jack",
    "Jackeline",
    "Jacki",
    "Jackie",
    "Jacklyn",
    "Jackson",
    "Jacky",
    "Jaclyn",
    "Jacob",
    "Jacoby",
    "Jacque",
    "Jacquelin",
    "Jacqueline",
    "Jacquelyn",
    "Kaaren",
    "Kacey",
    "Kaci",
    "Kacie",
    "Kacy",
    "Kade",
    "Kadeem",
    "Kaden",
    "Kadence",
    "Kadijah",
    "Kadin",
    "Kadyn",
    "Kaeden",
    "Kael",
    "Kaela",
    "Kaelyn",
    "Kahlil",
    "Kai",
    "Kaia",
    "Kaiden",
    "Lacey",
    "Laci",
    "Lacie",
    "Lacy",
    "Ladarius",
    "Laddie",
    "Ladonna",
    "Lady",
    "Lafayette",
    "Lafe",
    "Lahoma",
    "Laila",
    "Lailah",
    "Lainey",
    "Laisha",
    "Lakeisha",
    "Laken",
    "Lakendra",
    "Lakesha",
    "Lakeshia",
    "Mabel",
    "Mabell",
    "Mabelle",
    "Mable",
    "Mac",
    "Macarthur",
    "Mace",
    "Macel",
    "Maceo",
    "Macey",
    "Machelle",
    "Maci",
    "Macie",
    "Mack",
    "Mackenzie",
    "Macy",
    "Madaline",
    "Madalyn",
    "Madalynn",
    "Madden",
    "Nada",
    "Nadia",
    "Nadine",
    "Naima",
    "Najee",
    "Nakia",
    "Nakisha",
    "Nakita",
    "Nallely",
    "Namon",
    "Nan",
    "Nana",
    "Nanci",
    "Nancie",
    "Nancy",
    "Nanette",
    "Nanie",
    "Nanna",
    "Nannette",
    "Nannie",
    "Oakley",
    "Obe",
    "Obed",
    "Obie",
    "Ocie",
    "Octa",
    "Octave",
    "Octavia",
    "Octavie",
    "Octavio",
    "Octavius",
    "Oda",
    "Odalis",
    "Odalys",
    "Oddie",
    "Odelia",
    "Odell",
    "Odessa",
    "Odette",
    "Odie",
    "Pablo",
    "Page",
    "Paige",
    "Pairlee",
    "Paisley",
    "Paityn",
    "Pallie",
    "Palma",
    "Palmer",
    "Paloma",
    "Pam",
    "Pamala",
    "Pamela",
    "Pamelia",
    "Pamella",
    "Pandora",
    "Pansy",
    "Paola",
    "Paralee",
    "Paris",
    "Qiana",
    "Queen",
    "Queenie",
    "Quentin",
    "Quiana",
    "Quincy",
    "Quinn",
    "Quint",
    "Quinten",
    "Quintin",
    "Quinton",
    "Rachael",
    "Racheal",
    "Rachel",
    "Rachelle",
    "Racquel",
    "Rae",
    "Raegan",
    "Raekwon",
    "Raelynn",
    "Rafael",
    "Rafaela",
    "Rafe",
    "Ragna",
    "Raheem",
    "Rahn",
    "Rahsaan",
    "Rahul",
    "Raiden",
    "Raina",
    "Rakeem",
    "Sabastian",
    "Sabina",
    "Sable",
    "Sabra",
    "Sabrina",
    "Sada",
    "Sade",
    "Sadie",
    "Sadye",
    "Sage",
    "Saige",
    "Saint",
    "Sal",
    "Salena",
    "Salina",
    "Sallie",
    "Sally",
    "Salma",
    "Salome",
    "Salomon",
    "Tab",
    "Tabatha",
    "Tabetha",
    "Tabitha",
    "Tad",
    "Taft",
    "Tahj",
    "Tai",
    "Taina",
    "Taj",
    "Taja",
    "Takisha",
    "Tal",
    "Talan",
    "Talen",
    "Talia",
    "Taliyah",
    "Tallie",
    "Talmadge",
    "Talmage",
    "Ula",
    "Ulises",
    "Ulysses",
    "Una",
    "Unique",
    "Ura",
    "Urban",
    "Uriah",
    "Uriel",
    "Urijah",
    "Ursula",
    "Vada",
    "Val",
    "Valarie",
    "Valencia",
    "Valentin",
    "Valentina",
    "Valentine",
    "Valentino",
    "Valeria",
    "Valerie",
    "Valery",
    "Valinda",
    "Vallie",
    "Valorie",
    "Van",
    "Vance",
    "Vander",
    "Vanesa",
    "Vanessa",
    "Vannie",
    "Wade",
    "Waino",
    "Waldemar",
    "Waldo",
    "Walker",
    "Wallace",
    "Wally",
    "Walt",
    "Walter",
    "Walton",
    "Wanda",
    "Waneta",
    "Wanita",
    "Ward",
    "Wardell",
    "Warner",
    "Warren",
    "Wash",
    "Washington",
    "Watson",
    "Xander",
    "Xavier",
    "Xena",
    "Ximena",
    "Xiomara",
    "Xzavier",
    "Yaakov",
    "Yadiel",
    "Yadira",
    "Yael",
    "Yahaira",
    "Yahir",
    "Yair",
    "Yajaira",
    "Yamilet",
    "Yamilex",
    "Yancy",
    "Yandel",
    "Yareli",
    "Yaretzi",
    "Yaritza",
    "Yasmeen",
    "Yasmin",
    "Yasmine",
    "Yazmin",
    "Yee",
    "Zachariah",
    "Zachary",
    "Zachery",
    "Zack",
    "Zackary",
    "Zackery",
    "Zada",
    "Zadie",
    "Zaid",
    "Zaida",
    "Zaiden",
    "Zain",
    "Zaire",
    "Zakary",
    "Zana",
    "Zander",
    "Zandra",
    "Zane",
    "Zaniyah",
    "Zara"
]

export const cities = [
    "Hong Kong",
    "Bangkok",
    "London",
    "Macau",
    "Singapore",
    "Paris",
    "Dubai",
    "New York City",
    "Kuala Lumpur",
    "Istanbul",
    "Delhi",
    "Antalya",
    "Shenzhen",
    "Mumbai",
    "Phuket",
    "Rome",
    "Tokyo",
    "Pattaya",
    "Taipei",
    "Mecca",
    "Guangzhou",
    "Prague",
    "Medina",
    "Seoul",
    "Amsterdam",
    "Agra",
    "Miami",
    "Osaka",
    "Las Vegas",
    "Shanghai",
    "Ho Chi Minh City",
    "Denpasar",
    "Barcelona",
    "Los Angeles",
    "Milan",
    "Chennai",
    "Vienna",
    "Johor Bahru",
    "Jaipur",
    "Cancún",
    "Berlin",
    "Cairo",
    "Athens",
    "Orlando",
    "Moscow",
    "Venice",
    "Madrid",
    "Ha Long",
    "Riyadh",
    "Dublin",
    "Florence",
    "Hanoi",
    "Toronto",
    "Johannesburg",
    "Sydney",
    "Munich",
    "Jakarta",
    "Beijing",
    "Saint Petersburg",
    "Brussels",
    "Jerusalem",
    "Budapest",
    "Lisbon",
    "Dammam",
    "Penang Island",
    "Heraklion",
    "Kyoto",
    "Zhuhai",
    "Vancouver",
    "Chiang Mai",
    "Copenhagen",
    "San Francisco",
    "Melbourne",
    "Warsaw",
    "Marrakesh",
    "Kolkata",
    "Cebu City",
    "Auckland",
    "Tel Aviv",
    "Guilin",
    "Honolulu",
    "Hurghada",
    "Kraków",
    "Muğla",
    "Buenos Aires",
    "Chiba",
    "Frankfurt am Main",
    "Stockholm",
    "Lima",
    "Da Nang",
    "Batam",
    "Nice",
    "Fukuoka",
    "Abu Dhabi",
    "Jeju",
    "Porto",
    "Rhodes",
    "Rio de Janeiro",
    "Krabi",
    "Bangalore",
    "Mexico City",
    "Punta Cana",
    "São Paulo",
    "Zürich",
    "Montreal",
    "Washington D.C.",
    "Chicago",
    "Düsseldorf",
    "Boston",
    "Chengdu",
    "Edinburgh",
    "San Jose",
    "Tehran",
    "Houston",
    "Hamburg",
    "Cape Town",
    "Manila",
    "Bogota",
    "Xi'an",
    "Beirut",
    "Geneva",
    "Colombo",
    "Xiamen",
    "Bucharest",
    "Casablanca",
    "Atlanta",
    "Sofia",
    "Dalian",
    "Montevideo",
    "Amman",
    "Hangzhou",
    "Pune",
    "Durban",
    "Dallas",
    "Accra",
    "Quito",
    "Tianjin",
    "Qingdao",
    "Philadelphia",
    "Lagos"
]

export const occupations = [
    "911 Operator",
    "Able Seaman",
    "Accounting Professor",
    "Acid Dipper",
    "Activities Concierge",
    "Acupuncture Physician",
    "Admiral",
    "Adult English as a Second Language (ESL) Teacher",
    "Advanced Foreign Counterintelligence Officer (Afco)",
    "Advertising Agent",
    "Advertising Photographer",
    "Aerial Gunner, Superintendent",
    "Aeronautical Drafter",
    "Aerospace Control And Warning Systems, Weapons Director",
    "Agricultural Chemist",
    "Agricultural Extension Educator",
    "Agronomist",
    "Air Battle Manager",
    "Air Control Electronics Operator",
    "Air Intercept Controller Supervisor",
    "Air Support Operations Operator",
    "Airborne Mine Countermeasures (Amcm) Aircrewman",
    "Airborne Weapons Technical Manager",
    "Aircraft Engine Assembler",
    "Aircraft Launch And Recovery Equipment Maintenance Technician",
    "Aircraft Quality Control Inspector",
    "Airline Captain",
    "Airline Ticket Agent",
    "Airplane Rigger",
    "Airset Caster",
    "Algebraist",
    "Alternative Dispute Resolution Coordinator",
    "Ambulance Attendant",
    "Ammunition Officer",
    "An/Tsq-73 Air Defense Artillery Command And Control System Operator/Maintainer",
    "Anger Control Counselor",
    "Animal Cruelty Investigation Supervisor",
    "Animal Pathologist",
    "Animal Warden",
    "Anti-Tank Missileman",
    "Aoc Airspace Control Officer",
    "Aoc Operations - Combat Search And Rescue Officer",
    "Aoc Operations - Special Operations Officer",
    "Aoc Plans - Master Air Attack Planning Assistant Chief",
    "Apothecary",
    "Application Development Director",
    "Applied Psychology Professor",
    "Aquarist",
    "Arcade Supervisor",
    "Architectural Inspector",
    "Armed Guard",
    "Art Editor",
    "Artist Representative",
    "Asphalt Paving Machine Operator",
    "Assembling Motor Builder",
    "Assistant Counsel",
    "Astrophysicist",
    "Athletic Events Scorer",
    "Attorney General",
    "Auditor",
    "Auto Body Technician",
    "Auto Damage Insurance Appraiser",
    "Auto Phone Installer",
    "Auto Tire Worker",
    "Automobile Body Painter",
    "Automobile Rental Clerk",
    "Automotive Fuel Injection Servicer",
    "Automotive Service Writer",
    "Aviation Boatswain's Mate",
    "Aviation Resource Management Superintendent",
    "Back Hoe Operator",
    "Bagel Maker",
    "Ballet Professor",
    "Band Manager",
    "Bank Guard",
    "Banking Manager",
    "Banquet Supervisor",
    "Bareback Rider",
    "Barn Hand",
    "Bassoonist",
    "Beam Builder Helper",
    "Beef Splitter",
    "Bench Chemist",
    "Bicycle Mechanic",
    "Billboard Poster Helper",
    "Bindery Worker",
    "Biochemistry Technologist",
    "Biomedical Electronics Technician",
    "Biostatistics Professor",
    "Blanchard Grinder Operator",
    "Blind Escort",
    "Blow Mold Operator",
    "Boat Pilot",
    "Boiler Coverer",
    "Boiler Room Operator",
    "Book Critic",
    "Bookie",
    "Bore Mill Operator for Plastic",
    "Bottle Washing Machine Operator",
    "Brace Maker",
    "Brass and Wind Instrument Repairer",
    "Brewery Pumper",
    "Bricklayer",
    "Bridge Ironworker",
    "Broadcast Maintenance Engineer",
    "Budget Examiner",
    "Building Cleaning Supervisor",
    "Building Rental Manager",
    "Bulldozer Operator",
    "Bus Washer",
    "Business Process Consultant",
    "Button Sewing Machine Operator",
    "C2 Tactical Analysis Technician",
    "CNC Machinist",
    "CTRS",
    "Cadastral Mapper",
    "Calciner Operator",
    "Camera Repairer",
    "Cancer Registrar",
    "Cantor",
    "Car Rental Agent",
    "Cardiac Monitor Technician",
    "Cardiovascular Surgeon",
    "Cargo Router",
    "Carpet Layer Helper",
    "Carton Making Machine Operator",
    "Casino Cage Cashier",
    "Casino Supervisor",
    "Catalogue Clerk",
    "Cavalry Officer",
    "Census Clerk",
    "Ceramic Tile Installation Helper",
    "Certified Corporate Travel Executive",
    "Certified Health Education Specialist",
    "Certified Medical Assistant",
    "Certified Nurse Midwife (CNM)",
    "Certified Personal Chef",
    "Certified Prosthetist/Orthotist",
    "Certified Respiratory Therapist",
    "Chain Link Fence Installer",
    "Charter Pilot (Airline)",
    "Chef De Froid",
    "Chemical Munitions And Materiel Management",
    "Chemical Sales Representative",
    "Cherry Sorter",
    "Chief Jailer",
    "Child Abuse Worker",
    "Child Welfare Worker",
    "Children's Literature Professor",
    "Chinese Language Professor",
    "Choir Member",
    "Chrome Plater",
    "Cigarette Examiner",
    "Circuit Design Engineer",
    "City Collector",
    "Civil Computer-Aided Design and Drafting Technician",
    "Clarinetist",
    "Cleaning and Maintenance Worker",
    "Clinic Director",
    "Clinical Informatics Analyst",
    "Clinical Nurse Specialist",
    "Clinical Rehabilitation Aide",
    "Cloth Cutter",
    "Clothing Presser",
    "Coal Tram Driver",
    "Cocktail Server",
    "Coin Rolling Machine Operator",
    "Collections Clerk",
    "Columnist",
    "Combatant Diver Qualified (Officer)",
    "Comedian",
    "Command Post Superintendent",
    "Commercial Crabber",
    "Commodities Broker",
    "Communications Equipment Installer",
    "Community Health Nurse",
    "Compensation Director",
    "Composition Weatherboard Installer",
    "Computed Tomography (CT) Scanner Operator",
    "Computer Hardware Developer",
    "Computer Numerically Controlled (CNC) Milling Machine Operator",
    "Computer Repairer",
    "Computer Systems Security Analyst",
    "Concrete Batch Plant Operator",
    "Concrete Pavement Installer",
    "Conference Center Manager",
    "Conservation Enforcement Officer",
    "Construction Carpenters Helper",
    "Construction Inspector",
    "Construction Trench Digger",
    "Continuous Mining Machine Coal Miner",
    "Control Electrician",
    "Cook Chill Technician",
    "Copy Editor",
    "Cork Insulation Installer",
    "Corporate Attorney",
    "Corporate Statistical Financial Analyst",
    "Correctional Sergeant",
    "Corrugated Box Machine Operator",
    "Cost Analyst",
    "Cotton Picker",
    "Counterintelligence (Ci)/Human Source Intelligence (Humint) Officer",
    "County Commissioner",
    "Court Messenger",
    "Courtroom Clerk",
    "Crane Oiler",
    "Credit Assessment Analyst",
    "Credit Rating Checker",
    "Crew Dispatcher",
    "Criminalist Technician",
    "Crop Scout",
    "Cryptanalyst",
    "Cryptologic Support Specialist",
    "Cupola Repairer",
    "Curve Saw Operator",
    "Customer Complaint Clerk",
    "Cut Off Saw Operator",
    "DTP Operator",
    "Dairy Scientist",
    "Data Architect",
    "Data Operations Director",
    "Database Administration Manager",
    "Daycare Aide",
    "Deck Hand",
    "Degreaser Operator",
    "Dental Ceramist",
    "Dental Technician",
    "Deputy Bailiff",
    "Design Project Management Specialists",
    "Developmental Psychologist",
    "Dictaphone Typist",
    "Dietary Technician",
    "Digital Press Operator",
    "Dining Room Host",
    "Director of Civil Defense",
    "Discotheque Dancer",
    "Display Specialist",
    "Divinity Professor",
    "Doctor of Nurse Anesthesia Practice",
    "Dog Bather",
    "Dog Sitter",
    "Door Closer Mechanic",
    "Dragline Mechanic",
    "Dredge Mate",
    "Drilling Rig Operator",
    "Druggist",
    "Drywall Finisher",
    "Drywall Taper Helper",
    "Dye Range Operator",
    "EMS Director",
    "Early Childhood Teacher",
    "Echocardiographer",
    "Economic Development Specialist",
    "Education Counselor",
    "Egg Gatherer",
    "Electric Golf Cart Repairers",
    "Electric Sewer Cleaning Machine Operator",
    "Electrical Controls Assembler",
    "Electrical Estimator",
    "Electrical Sign Wirer Helper",
    "Electro Plater",
    "Electromechanical Assembler",
    "Electronic Engineer",
    "Electronic Musical Instrument Repairer",
    "Electronic Publishing Specialist",
    "Electronic Warfare Officer",
    "Electronics Technology Instructor",
    "Elementary School Inclusion Teacher",
    "Elevator Inspector",
    "Embedded Systems Software Developer",
    "Emergency Medical Service Coordinator",
    "Emergency Planner",
    "Emitter Location/Identification Technician",
    "Employee Placement Specialist",
    "Endoscopy Registered Nurse",
    "Engineering Psychologist",
    "Enologist",
    "Environmental Communications Specialist",
    "Environmental Health Sanitarian",
    "Environmental Science Technician",
    "Equal Employment Opportunity Investigator",
    "Equity Trader",
    "Estate Conservator",
    "Ethnologist",
    "Excavating Supervisor",
    "Exhibitions and Collections Manager",
    "Experimental Psychologist",
    "Extrusion Press Operator",
    "Fabric Awning Repairer",
    "Falafel Cart Cook",
    "Family Practice Physician Assistant",
    "Family Service Center Director",
    "Farm Business Management Agent",
    "Farrowing Worker",
    "Feed Mixer Operator",
    "Fermenter",
    "Fiber Optic Technician",
    "Fiberglass Ski Maker",
    "Field Artillery Senior Sergeant",
    "File Keeper",
    "Film Printer",
    "Financial Compliance Examiner",
    "Fingerprint Clerk",
    "Fire Control Officer (Surface-To-Air Missiles)",
    "Fire Equipment Operator",
    "Fire Prevention Inspector",
    "Firebrick Layer Helper",
    "Fish Hatchery Supervisor",
    "Fixed Capital Clerk",
    "Flat Sorting Machine Clerk",
    "Flight Data Technician",
    "Flight Paramedic",
    "Floor Cleaner",
    "Floral Decorator",
    "Fluid Pump Operator",
    "Food Preparer",
    "Food Service Supervisor",
    "Foreign Banknote Teller",
    "Forensic Materials Engineer",
    "Forest Ecology Professor",
    "Forest Technician",
    "Forging Roll Operator",
    "Fortune Teller",
    "Fracturing Derrick Operator",
    "Freight Car Repairer",
    "Freight Inspector",
    "Frozen Yogurt Maker",
    "Fumigator",
    "Funeral Car Driver",
    "Fur Tailor",
    "Furniture Refinisher",
    "GPS Car Navigation Installer",
    "Gambling Department Head",
    "Game Warden",
    "Gas Appliance Repairer",
    "Gas Furnace Installer",
    "Gas Plumber",
    "Gastroenterologist",
    "Gemologist",
    "General Internal Medicine Doctor",
    "Generator Assembler",
    "Geological Drafter",
    "Geomorphologist",
    "Geoscientist",
    "German Professor",
    "Glass Block Bender",
    "Glass Tube Bender",
    "Go-Cart Mechanic",
    "Golf Course Architect",
    "Government Service Executive",
    "Grain Roaster",
    "Grapple Skidder Operator",
    "Greenskeeper",
    "Grocery Light Truck Driver",
    "Grounds Crew Supervisor",
    "Guidance Counselor",
    "Guitar Player",
    "Gwot Ia/Ilo Intelligence Support",
    "Gyroscope Repairer",
    "Hair Stylist",
    "Hand Fabric Cutter",
    "Hand-Woven Carpet and Rug Mender",
    "Hard Rock Drill Operator",
    "Harpoon (An/Swg-1a) Engagement Planning Operator",
    "Hat Designer",
    "Hay Stacker Operator",
    "Head Custodian",
    "Headend Technician",
    "Health Equipment Servicer",
    "Health Physicist",
    "Healthcare Manager",
    "Hearse Driver",
    "Heating, Ventilation, and Air Conditioning (HVAC) Mechanic Boiler Operator",
    "Helicopter Airframe Mechanic",
    "Helicopter Utility Aircrewman",
    "Herpetologist",
    "High School Biology Teacher",
    "High School Special Education Resource Teacher",
    "Highway Painter",
    "Histologist Technologist",
    "Historiography Professor",
    "Home Demonstrator",
    "Home Mortgage Disclosure Act Specialist",
    "Homeowner Association Manager",
    "Horologist",
    "Hospice Director",
    "Hospital Chaplain",
    "Hot Dog Vender",
    "Hotel Front Desk Clerk",
    "House Carpenter",
    "House Wirer Helper",
    "Human Resources Generalist",
    "Hydraulic Pile Hammer Operator",
    "Hydroelectric Plant Operator",
    "IT Professor",
    "Ice Skating Coach",
    "Immigration Investigator",
    "In-Flight Refueling System Repairer",
    "Incoming Freight Clerk",
    "Individual Pension Adviser",
    "Industrial Conveyor Belt Repairer",
    "Industrial Gas Fitter",
    "Industrial Production Manager",
    "Industrial Roofer Helper",
    "Infantry Unit Leader",
    "Information Systems Director",
    "Ingot Caster",
    "Insecticide Expert",
    "Institutional Cook",
    "Insurance Attorney",
    "Insurance Sales Supervisor",
    "Intelligence Officer, Basic",
    "Interface Control Officer (Ico)",
    "Internal Auditor",
    "International Student Counselor",
    "Inventory Control Clerk",
    "Iron Guardrail Installer",
    "Jail Guard",
    "Jewelry Grinder",
    "Job Analyst",
    "Joint Chemical, Biological, Radiological, Nuclear Reconnaissance System Operator (Jcbrnrs) Lav Operator",
    "Joint Terminal Attack Controller Instructor (Jtac-I)",
    "Junior High School Business Teacher",
    "Juvenile Corrections Officer",
    "Kennel Worker",
    "Keypunch Operator",
    "Kitchen Chef",
    "Knitting Machine Operator",
    "LVN",
    "Labor Training Manager",
    "Ladle Repairer",
    "Land Management Forester",
    "Landscape Architect",
    "Large Animal Veterinarian",
    "Laundry Equipment Operator",
    "Lawn Caretaker",
    "Lead Abatement Worker",
    "Leather Worker",
    "Lens Grinder",
    "Library Cataloging Technician",
    "License Clerk",
    "Licensed Embalmer",
    "Licensed Optical Dispenser",
    "Licensed Veterinary Technician",
    "Light Rail Signal Technician",
    "Lime Filter Operator",
    "Linoleum Layer Helper",
    "Lithograph Press Operator",
    "Loader Operator",
    "Lobby Attendant",
    "Lock Setter",
    "Locomotive Electrician",
    "Log Hauler",
    "Log Truck Tractor-Trailer Driver",
    "Logging Flatbed Truck Driver",
    "Logging Truck Driver",
    "Long Distance Operator",
    "Loom Operator",
    "Luggage Repairer",
    "M1 Armor Crewman",
    "Machine Builder",
    "Machinery Appraiser",
    "Magnetic Healer",
    "Maintenance Dispatcher",
    "Management Consultant",
    "Manufacturing Director",
    "Map Maker",
    "Marine Air Ground Task Force (Magtf) Planners",
    "Marine Drafter",
    "Marine Equipment Engineer",
    "Marine Propulsion Technician",
    "Market Research Analyst",
    "Marketing Instructor",
    "Masseur",
    "Master Naval Parachutist",
    "Maternal-Fetal Medicine Physician",
    "Maxillofacial Pathology",
    "Meat Curer",
    "Meat and Poultry Inspector",
    "Mechanics Handyman",
    "Medical Billing Supervisor",
    "Medical Librarian",
    "Medical Records Administrator",
    "Medical and Health Information Manager",
    "Memorial Mason",
    "Merchant Seaman",
    "Metal Grinder",
    "Metal Roofing Mechanic",
    "Metallographer",
    "Meter Maid",
    "Microwave Oven Assembler",
    "Military Science Instructor",
    "Mill Recorder",
    "Mineral Engineer",
    "Mining Backhoe Operator",
    "Mining Payloader Operator",
    "Missile Navigation Systems Sales Engineer",
    "Mobile Applications Developer",
    "Modeling Agent",
    "Money Order Clerk"
]